"""empty message

Revision ID: 42f772f75dcc
Revises: 017328f6b8b6
Create Date: 2023-06-29 05:04:32.389408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f772f75dcc'
down_revision = '017328f6b8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draq_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drac_q', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drac_quotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drac_quotes',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('drac_q', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('draq_quotes')
    # ### end Alembic commands ###
